# Generated by Django 3.2 on 2021-06-23 21:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='试卷标题')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='试题内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '试卷管理',
                'verbose_name_plural': '试卷管理',
            },
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='页面标题')),
                ('user_info_content', tinymce.models.HTMLField(verbose_name='考生须知')),
                ('page_footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='页脚标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '页面信息',
                'verbose_name_plural': '页面信息',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, verbose_name='考室名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '考室管理',
                'verbose_name_plural': '考室管理',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='考生姓名')),
                ('candidate_num', models.CharField(max_length=100, unique=True, verbose_name='准考证号')),
                ('password', models.CharField(default='123456', max_length=256, verbose_name='登录密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwbs.room', verbose_name='所在考室')),
            ],
            options={
                'verbose_name': '考生管理',
                'verbose_name_plural': '考生管理',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_check', models.BooleanField(default=False, verbose_name='是否勾选')),
                ('is_begin', models.BooleanField(default=False, verbose_name='是否开始答题')),
                ('is_over', models.BooleanField(default=False, verbose_name='是否结束考试')),
                ('word_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Word文件名')),
                ('pdf_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='PDF文件名')),
                ('login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='登录IP')),
                ('login_os', models.CharField(blank=True, max_length=50, null=True, verbose_name='登录操作系统')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gwbs.user', verbose_name='考生')),
            ],
            options={
                'verbose_name': '作答记录',
                'verbose_name_plural': '作答记录',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='提交文件名')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='文件类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='提交时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gwbs.user', verbose_name='考生')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
            },
        ),
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_begin_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('exam_end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gwbs.examcontent', verbose_name='试卷标题')),
            ],
            options={
                'verbose_name': '考试时间',
                'verbose_name_plural': '考试时间',
            },
        ),
    ]
